name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: "1.18.1-otp-27"
            otp: "27.2.4"
          - elixir: "1.16.3-otp-26"
            otp: "26.2.5.6"
          - elixir: "1.14.3"
            otp: "25.2.3"
          - elixir: "1.13.4"
            otp: "24.3.4"
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v4

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install and compile dependencies
        run: mix deps.get --only test && mix deps.compile

      - name: Check for unused dependencies
        run: mix deps.get && mix deps.unlock --check-unused

      - name: Compile project
        run: mix compile --all-warnings --warnings-as-errors

      - name: Run tests
        run: mix check
